version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: remind-me-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: remindme.1234
      POSTGRES_DB: remind_me
    # Ports removed to not expose to host machine
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - remind-me-net
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: remind-me-backend
    command: sh -c "npx prisma migrate deploy && npm start"
    environment:
      DATABASE_URL: postgresql://admin:remindme.1234@postgres:5432/remind_me
      PORT: 3000
    ports:
      - "3016:3000"
    depends_on:
      - postgres
    networks:
      - remind-me-net
    restart: always

  frontend:
    build: ./frontend
    container_name: remind-me-frontend
    ports:
      - "4206:80"
    depends_on:
      - backend
    networks:
      - remind-me-net
    restart: always

volumes:
  postgres_data:


networks:
  remind-me-net:


